---

- name: Create a droplet
  community.digitalocean.digital_ocean_droplet:
    state: present
    oauth_token: "{{ lookup('ansible.builtin.env', '{{set_token}}') }}"
    name: "{{ set_hostname }}.{{set_fqdn}}"
    size: s-1vcpu-1gb
    region: sfo3
    image: ubuntu-20-04-x64
    wait_timeout: 500
    ssh_keys: "{{set_sshkey}}"
  register: set_droplet

#- name: Create a corresponding domain
#  community.digitalocean.digital_ocean_domain:
#    state: present
#    name: "{{ set_droplet.droplet.name }}.{{set_fqdn}}"
#    ip: "{{ set_droplet.droplet.ip_address }}"

- name: Create A record for www
  community.digitalocean.digital_ocean_domain_record:
    state: present
    oauth_token: "{{ lookup('ansible.builtin.env', '{{set_token}}') }}"
    domain: "{{ set_hostname }}.{{set_fqdn}}"
    type: A
    name: www
    data: "{{ set_droplet.droplet.ip_address }}"

