---

#- name: Create a droplet
#  community.digitalocean.digital_ocean_droplet:
#    state: present
#    api_token: "{{ set_token }}"
#    name: "{{ set_hostname }}.{{set_fqdn}}"
#    size: s-1vcpu-1gb
#    region: sfo3
#    image: ubuntu-20-04-x64
#    wait_timeout: 500
#    ssh_keys: "{{set_sshkey}}"
#  register: set_droplet
- name: Gather information about domain with given name
  community.digitalocean.digital_ocean_domain_info:
    oauth_token: "{{ set_token }}"
    domain_name: "thespot.rocks"
- debug:
    msg: "ID is {{ my_droplet.droplet.id }}"

- debug:
    msg: "IP is {{ my_droplet.droplet.ip_address }}"


#- name: Create A record for www
#  community.digitalocean.digital_ocean_domain_record:
#    state: present
#    api_token: "{{ set_token }}"
#    domain: "{{ set_hostname }}.{{set_fqdn}}"
#    type: A
#    name: www
#    data: "{{ set_droplet.droplet.ip_address }}"

