---
- hosts: all
  become: true
  become_user: root

  tasks:
  #- name: Reboot a machine
      #   reboot:
            
  - name: Install sudo Debian
    apt:
      name: sudo
      state: present
    when: ansible_os_family == 'Debian'
    
  - name: Install sudo Redhat
    yum:
      name: sudo
      state: present
    when: ansible_os_family in ['RedHat', 'Rocky']
    
  - name: Allow 'sudo' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%sudo'
      line: '%sudo ALL=(ALL:ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'


  - name: Add sudoers users to sudo group
    user:
      name=ops
      groups=sudo
      append=yes
      state=present
      shell=/bin/bash
      createhome=yes
      password=B0sspasswd01!!
      generate_ssh_key=yes
      ssh_key_bits=2048
      ssh_key_file=.ssh/id_rsa      
    when: ansible_os_family == 'Debian' 

  - name: Add sudoers users to wheel group
    user:
      name=ops
      groups=wheel
      append=yes
      state=present
      shell=/bin/bash
      createhome=yes
      password=B0sspasswd01!!
      generate_ssh_key=yes
      ssh_key_bits=2048
      ssh_key_file=.ssh/id_rsa
    when: ansible_os_family in ['RedHat', 'Rocky']
        
  - name: Download .ssh/id_rsa
    ansible.builtin.get_url:
      url: https://github.com/Nieuwhof/ansible/tree/main/pubkey/Opskey/id_rsa
      dest: /home/ops/.ssh/ops_id_rsa
      mode: '0440'

  - name: Download .ssh/id_rsa.pub
    ansible.builtin.get_url:
      url: https://github.com/Nieuwhof/ansible/tree/main/pubkey/Opskey/id_rsa.pub
      dest: /home/ops/.ssh/ops_id_rsa.pub
      mode: '0440'      

  - name: Set authorized keys
    ansible.posix.authorized_key:
      user: ops
      state: present
      manage_dir: yes
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCvst/FJr+7BJX98grW3DyXqwwJfb5p5ZyVYdlV0vuGdG4nPg2fos0zT+nx14r1k4Xv+zAVYSME4Zl30hl1UFeKf+bfFidi1/RkyYuy6/FsOnJYkf4LjUOC8c0in5SQrMBS//AyuRQOQWIBt7yjLfHMafSdNUbNIZq34/AmpQwMETWbjeSi9QBxhyRL0PVl22ltWyh31wtXiIaAivllJtoxQuWBjoTwqPaBX8qA73zXNvLypvEKjvBFi7hRW5BHOYyOAztFrk7cYTv+9hqJi0LhUe2YVeihHtZUzzlHgxxrsYjXI217gpJHlijkClv7va0BocWrC5P+hHVKUuqvvn3ZDks3YJKFsy8+Uu1a0f6UVELeVUHvh0l8aRQmP9/rIiWzGcgIOLRKhR0nzdWBK/xydhNNYAMsHz4U+mfFQfLqrC28PCkEjbZlmsTJDX9vYDW36wbON5PsftrTzWKBROEkAlKElgqQ2TB8xFJvWHbgUht4rtwssQjb9dRVpTg/k7E= ops@wallace"


#  - name: copy Opskey to /home/ops/.ssh/
#    copy:
#      src: /cloud/ansible/pubkey/Opskey/
#      dest: /home/ops/.ssh
#      remote_src: true
#    become: true
      
  - name: install packages Debian
    apt:
        state: present
        name:
        - python3
        - pip
        - htop
        - nano
    when: ansible_os_family == 'Debian'       

  - name: install packages Redhat
    yum:
        state: present
        name:
        - python3
        - pip
        - nano
    when: ansible_os_family in ['RedHat', 'Rocky']       
