---
- hosts: all
  become: true
  become_user: root

  tasks:
   - name: Reboot a machine
     reboot:
     
- name: Install sudo
  apt:
     name: sudo
     state: present

- name: Allow 'sudo' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL:ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'


- name: Add sudoers users to sudo group
  user:
    name=ops
    groups=sudo
    append=yes
    state=present
    shell=/bin/bash
    createhome=yes
    password=B0sspasswd01!!
    
- name: Create a 2048-bit SSH key for user ops in ~ops/.ssh/id_rsa
  ansible.builtin.user:
    name: ops
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    
