---
- hosts: all
  become: true
  become_user: root

  tasks:
   - name: Reboot a machine
     reboot:
     
- name: Install sudo
  apt:
     name: sudo
     state: present

- name: Allow 'sudo' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL:ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'


- name: Add sudoers users to sudo group
  user:
    name="{{ item }}"
    groups=sudo
    append=yes
    state=present
    shell=/bin/bash
    createhome=yes
  with_items:
        - ops
