---
- name: Create new DigitalOcean VPS
  hosts: all
  become: true
  become_user: root

  vars:
    droplet_name: preston
    digital_ocean_token0: dop_v1_f8b675f60b067f786bece
    digital_ocean_token1: 078daca5aa51c7b5d3565c76b1b4462066f0ea8beb7
    droplet_size: s-1vcpu-512mb-10gb
    droplet_region: FRA1
    droplet_image: ubuntu-20-04-x64
    droplet_ssh_key: ee:18:46:e4:0e:89:83:9c:10:de:a2:a5:fc:ff:ee:5e

  #  droplet:
  #   - droplet_name: preston
  roles:
    - oceannewvps
