---
- hosts: localhost
  become: True
  become_user: root

  vars:
    DO_API_TOKEN: dop_v1_1dec172871d52cd45546a7e45f4b7042b8edd934059f9c8cd39db1cb78175204

  roles:
     - oceannewvps
    