---   
- hosts: myregistry
  gather_facts: false
  connection: local
  collections:
    - awx.awx
  vars_files:
    - roles/playground/vars/ansible.yml
  become: True
  become_user: root

  roles:
    # - updateos
    - playground
