---
- hosts: all
  become: true
  become_user: root
  
  vars:
   account:
    - name: arnold 
      group: root
    - name: bolti
      group: root
    
  tasks:
     - name: Loop test create users
       user:
          name: '{{ item }}' 
          group: '{{ item }}' 
          state: present
       loop: '{{ account }}'
          
