---
- hosts: all
  become: true
  become_user: root
  
  vars:
   account:
    - { name: arnold ,  group: sudo }
    - { name: bolti ,   group: sudo }
    
  tasks:
     - name: Loop test create users
       user:
          name: '{{ item.name }}' 
          group: '{{ item.group }}' 
          state: present
       loop: '{{ account }}'
       register:  my_test 

     - name: "Print the my_test"
       ansible.builtin.debug:
#          msg:  System {{ inventory_hostname }} has IP {{ ansible_default_ipv4.address }}    
        var: my_test.home