---
- hosts: bigpants
  become: true
  become_user: root
  tasks:

  - name: uritest
    uri:
      url: https://devopsjunction.com
    register: result

  - name: debugging
    debug: 
      var: result
      verbosity: 2
