---
- name: be sure nginx is installed
  apt:
    name: nginx
    state: present

- name: be sure nginx is configured
  template:
    src: index.nginx-debian.html.j2
    dest: /var/www/html
  #notify:
  # - restart nginx

#- name: Generate /etc/hosts file
#  template:
#    src=hosts.j2
#    dest=/etc/hosts
    
