---
- name: Create and push container image with Ansible Builder
  hosts: localhost
  connection: local
  vars:
    acc_username: 'bnieuwhof'
    container_image: 'ee220424'
    container_tags:
      - latest
      - 2.0
    requirements_file: requirements.txt
    collections_file: requirements.yml
    bindep_file: bindep.txt
  tasks:
    - name: Install Ansible Builder
      pip:
        name: ansible-builder
        state: present

    - name: Create requirements.yml
      copy:
        content: |
          ---
          collections:
            - community.docker
            - awx.awx
            - ansible.utils
            - community.general
            - community.digitalocean
        dest: "{{ collections_file }}"

    - name: Create requirements.txt
      copy:
        content: |
          # List your Python dependencies here
          # For example:
          #  requests
             paramiko
        dest: "{{ requirements_file }}"

    - name: Create bindep.txt
      copy:
        content: |
          # List your system dependencies here
          # For example:
          # python3-devel
          # libffi-devel
          #  findutils
          #  net-tools
          #  curl
          #  gcc
          #  git
          #  libffi-dev
          #  libpython3-dev
          #  libssl-dev
          #  lsb-release
          #  make
          #  python3-full
          #  wget
          #  ansible

          # Base requirements for Ubuntu
            git-core          [platform:dpkg]
            libssl-dev        [platform:dpkg]
            libffi-dev        [platform:dpkg]
            python3           [platform:dpkg]
            python3-apt       [platform:dpkg]
            python3-dev       [platform:dpkg]

          # Base requirements for RPM distros
            gcc-c++           [platform:rpm]
            git               [platform:rpm]
            libffi-devel      [platform:rpm]
            openssl-devel     [platform:rpm]
            python3-devel     [platform:rpm]
            net-tools         [platform:rpm]

        dest: "{{ bindep_file }}"

    - name: Log into container registry
      community.docker.docker_login:
        username: "{{ acc_username }}"
        password: "NY8gqtaa01!!"

    - name: Build container image with Ansible Builder
      command: ansible-builder build -v3 -t "{{ container_image }}"
      args:
        chdir: "{{ playbook_dir }}"
      register: build_output

    - name: Build image with Ansible Builder
      command: ansible-builder build -v3 -t "{{ container_image }}"

    - name: Tag final
      command: docker tag "{{ container_image }}" "{{ acc_username }}/{{ container_image }}:{{ item }}"
      loop: "{{ container_tags }}"

    - name: Push container image to container registry
      command: docker push "{{ acc_username }}/{{ container_image }}:{{ item }}"
      loop: "{{ container_tags }}"
      
