---

- name: Create user account - {{ pass }}
  user: name=ops
        pass = "{{ newpassword|password_hash('sha512') }}"
        password="{{ pass }}"
        state=present
        append=yes
        shell="/bin/bash"
        update_password=always

