---

- name: Create user account
  user: name=ops
        groups=sudo
        state=present
        append=yes
        shell="/bin/bash"
        
- name: Password Set Root
  shell: echo root:"{{set_pass}}" | chpasswd

- name: Password Set Ops
  shell: echo ops:"{{set_pass}}" | chpasswd       



