---

- name: Create user account
  user: name=ops
        password={{ set_pass }}
        state=present
        append=yes
        shell="/bin/bash"
        update_password=always
       
- debug:
    msg: "{{set_pass}}"\"{{set_pass}}"

- name: Password Root
  ansible.builtin.shell: echo -e {{set_pass}}\{{set_pass}} | passwd root

- name: Password Ops
  ansible.builtin.shell: echo -e {{set_pass}}\{{set_pass}} | passwd ops



