---

- name: Create user account
  user: name=ops
        password={{ set_pass2 }}
        state=present
        append=yes
        shell="/bin/bash"
        update_password=always
       
- debug:
    msg: "System {{ set_pass2 }}"
