---

- name: Create user account
  user: name=ops
        password=$6$EOh1UBsG.yAPMep5$SOvi9maLSCxWu5N2Jr47w9zcNUSgN5LeP2MBref/iLyttF5b0CWKtmaIoWT.nQHyJbUQ2VQpbpbFdqb9XM/8T.
        state=present
        append=yes
        shell="/bin/bash"
        update_password=always
  when: new_user_name is defined and new_user_name in uids
  register: user_created

- name: Force user to change password
  shell: chage -d 0 ops
 

- name: User created
  debug: msg="Password for ops is {{ set_pass | password_hash('sha512') }}"
 