---

- name: Create user account
  user: name=ops
        groups=sudo
        state=present
        append=yes
        shell="/bin/bash"

- name: Password Root
  shell: echo -e "{{set_pass}}\n{{set_pass}}" | passwd root

- name: Password Ops
  shell: echo -e "{{set_pass}}\n{{set_pass}}" | passwd ops



