---

- name: Create user account
  user: name=ops
        password={{ set_pass|password_hash('sha512') }}
        state=present
        append=yes
        shell="/bin/bash"
        update_password=always
       
- name: Print
message debug:
msg: "This is machine is {{ ansible_hostname }} with IP {{ ansible_default_ipv4.address }}"