---

- name: Create user account
  vars:
      set_pass2: "{{ set_pass|password_hash('sha512') }}"
  user: name=ops
        password={{ set_pass2 }}
        state=present
        append=yes
        shell="/bin/bash"
        update_password=always
       
- name: Print some debug information 
  vars: 
    msg:
        Ansible Distribution: {{ set_pass2 }}
        Ansible Dist version: {{ ansible_distribution_version }}
  debug: 
    msg: "{{ msg.split('\n') }}"  