---

- name: Create user account
  user: name=ops
        password={{ set_pass }}
        state=present
        append=yes
        shell="/bin/bash"
        update_password=always
       
- debug:
    msg: "{{ set_pass }}"
