---

- name: Create user account
  user: name=ops
        password="$1$some_pla$lmVKJwdV3Baf.o.F0OOy71"
        state=present
        append=yes
        shell="/bin/bash"
        update_password=always
 