---

#- block:     # for redhat
    
- name: Update all packages to their latest version
  ansible.builtin.dnf:
    name: "*"
    state: latest
    when: ansible_os_family == "RedHat"

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
    when: ansible_os_family == "Debian"
