---

#- block:     # for redhat
    
- name: Update packages list Redhat
  dnf: "name=* state=latest"
  when: ansible_os_family == 'RedHat'

- name: Upgrade all RedHat packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
  when: ansible_os_family == 'RedHat'

- name: Update packages Debian list
  apt: update_cache=yes
  when: ansible_os_family == 'Debian'

- name: Upgrade packages Debian
  apt: upgrade=safe
  when: ansible_os_family == 'Debian'
