---

    - name: Load variables from vars/ansible.yml
      include_vars:
        file: vars/ansible.yml
    - name: Add user
      awx.awx.user:
        username: jdoe
        password: foobarbaz
        email: jdoe@example.org
        first_name: John
        last_name: Doe
        state: present
      
