---

#    - name: Load variables from vars/ansible.yml
#      include_vars:
#        file: vars/ansible.yml
    
    - name: Create organization
      awx.awx.application:
        api_url: 'http://myregister.bertus.cloud'
        api_username: 'admin'
        api_password: 'B0sspasswd01!!'
        state: present  
        resource: organization
        name: 'Organixation Description'
      register: result
      
