---

    - name: Load variables from vars/ansible.yml
      include_vars:
        file: vars/ansible.yml
    
    - name: Create organization
      tower_organization:
        name: "Foo"
        description: "Foo bar organization"
        state: present
        controller_config_file: "~/tower_cli.cfg"
      
