---
- name: Assign user as a system administrator
  awx.awx.user:
    username: "{{ item.value.name }}"
    password: "{{ item.value.pass }}"
    email: jdoe@example.org
    superuser: true
    state: present
  loop: "{{ users | dict2items }}"

- name: Establish organization
  awx.awx.organization:
    name: "{{ item.value.name }}"
    description: "Organization for Foo bar"
    state: present
  loop: "{{ organizations | dict2items }}"

- debug:
      msg: "The user {{ item.key }} is named: {{ item.value.name }}"
  loop: "{{ users | dict2items }}"
