---
- name: "example with encrypted variables"
  block:
    - name: "msg password"
      block:
        - debug:
            msg: "password is {{ userpassword }}"
  vars_files:
    - secrets.yml
  tasks:
    - name: "msg password"
      block:
        - debug:
            msg: "password is {{ userpassword }}"