---

#    - name: Load variables from vars/ansible.yml
#      include_vars:
#        file: vars/ansible.yml
    
    - name: Create organization
      awx.awx.organization:
        api_url: 'http://myregistry.bertus.cloud:8080/api/'
        api_token: '7CW9F5txvt7HrXFIanW2c93lcFTVb1'
        state: present  
 #       resource: organization
        name: 'Organixation Description'
        description: 'Organixation Description'
        ee: true
      register: result
      
