---

    - name: Load variables from vars/ansible.yml
      include_vars:
        file: vars/ansible.yml

    - name: Create User
      user:
        name: "{{ item.user_name }}"
        password: "{{ item.user_password }}"
        email: "{{ item.user_email }}"
        state: present
      with_items: "{{ users }}"

    - name: Add Organization
      organization:
        name: "{{ item.organization_name }}"
        state: present
      with_items: "{{ organizations }}"
      
