---
- name: Add user as a system administrator
  awx.awx.user:
    username: "{{ item.value.name }}"
    password: "{{ item.value.pass }}"
    email: jdoe@example.org
    superuser: yes
    state: present

- name: Create organization
  awx.awx.organization:
    name: "{{ item.value.name }}"
    description: "Foo bar organization"
    state: present

- debug:
      msg: "User {{ item.key }} has name: {{ item.value.name }}"
  loop: "{{ users | dict2items }}"
