---

    - name: Load variables from vars/ansible.yml
      include_vars:
        file: vars/ansible.yml
    
    - name: Create organization
      organization:
        name: "Foo"
        description: "Foo bar organization"
        state: present  
