---

#    - name: Load variables from vars/ansible.yml
#      include_vars:
#        file: vars/ansible.yml
    
    - name: Create organization
      awx.awx.organization:
        api_url: 'http://myregistry.bertus.cloud:8080/api/'
        api_username: 'admin'
        api_password: 'B0sspasswd01!!'
        state: present  
 #       resource: organization
        name: 'Organixation Description'
        description: 'Organixation Description'
      register: result
      
