---
- name: Add user as a system administrator
  user:
    username: "{{ item.value.name }}"
    password: "{{ item.value.pass }}"
    email: jdoe@example.org
    superuser: yes
    state: present

- name: Create organization
  organization:
    name: "{{ item.value.name }}"
    description: "Foo bar organization"
    state: present
    
