---
#  - name: "add public ssh key to digitalocean account"
#    digital_ocean_sshkey:
#      name: "MacBook Pro"
#      oauth_token: "{{ digital_ocean_token }}"
#      ssh_pub_key: "{{lookup('file', '~/.ssh/ops_id_rsa.pub') }}"
#      state: present
#    register: sshkey_result

  - name: create a new droplet assigning the key
    digital_ocean_droplet:
      name: "{{ item }}"
      oauth_token: "{{ digital_ocean_token0 }}{{ digital_ocean_token1 }}"
      size: "{{ droplet_size }}"
      region: "{{ droplet_region }}"
      image: "{{ droplet_image }}"
      wait_timeout: 600
      unique_name: yes
      ssh_keys: "{{ set_sshkey }}"      
      state: present
    with_inventory_hostnames:
      - wg
    register: droplet_result

  - name: save ip and hostname to local hosts file /etc/hosts
    become: True
    lineinfile:
      path: /etc/hosts
      regexp: '.*{{ item.data.droplet.name }}$'
      line: "{{ item.data.ip_address }}  {{ item.data.droplet.name }}"
    with_items: "{{ droplet_result.results }}"




