---
  - name: Create a droplet with ssh key
    community.digitalocean.digital_ocean:
      state: present
      oauth_token: "{{ DO_API_TOKEN }}"
      #ssh_key_ids: 123,456
      name: mydroplet
      size_id: 2gb
      region_id: ams2
      image_id: fedora-19-x64
