---
- name: Create a new Droplet
  community.digitalocean.digital_ocean_droplet:
    state: present
    oauth_token: "{{ digital_ocean_token0 }}{{ digital_ocean_token1 }}"
    name: "{{ item }}"
    size: "{{ droplet_size }}"
    region: "{{ droplet_region }}"
    image: "{{ droplet_image }}"
    wait_timeout: 500
    ssh_keys: "{{ droplet_ssh_key }}"
    loop: 
      - "server1"
      - "server2"
  register: my_droplet

- name: Show Droplet info
  ansible.builtin.debug:
    msg: |
      Droplet ID is {{ my_droplet.data.droplet.id }}
      First Public IPv4 is {{ (my_droplet.data.droplet.networks.v4 | selectattr('type', 'equalto', 'public')).0.ip_address | default('<none>', true) }}
      First Private IPv4 is {{ (my_droplet.data.droplet.networks.v4 | selectattr('type', 'equalto', 'private')).0.ip_address | default('<none>', true) }}