---
- name: Create a new Droplet
  community.digitalocean.digital_ocean_droplet:
    state: present
    oauth_token: "{{ digital_ocean_token0 }}{{ digital_ocean_token1 }}"
    name: mydroplet
    size: s-1vcpu-1gb
    region: sfo3
    image: ubuntu-20-04-x64
    wait_timeout: 500
    ssh_keys: [ee:18:46:e4:0e:89:83:9c:10:de:a2:a5:fc:ff:ee:5e]
  register: my_droplet

