---
- name: Create a /cloud directory if it does not exist
  ansible.builtin.file:
    path: /cloud
    state: directory
    mode: 1755

- name: Clone a ansible script github repository
  git:
    repo: https://github.com/Nieuwhof/ansible.git
    dest: /cloud/ansible/
    clone: yes
    update: yes

- name: Clone a multipass scripts github repository
  git:
    repo: https://github.com/Nieuwhof/multipass.git
    dest: /cloud/multipass/
    clone: yes
    update: yes

- name: Update Upgrade
  apt:
    name: "*"
    state: latest

- name: Set a hostname
  ansible.builtin.hostname:
    name: wallace

- name: Install sudo
  apt:
     name: sudo
     state: present

- name: Allow 'sudo' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL:ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'


- name: Add sudoers users to sudo group
  user:
    name="{{ item }}"
    groups=sudo
    append=yes
    state=present
    createhome=yes
  with_items:
        - ops

#- name: Set up authorized keys for the root user
#  authorized_key: 
#       user: root
#       state: present
#       key: "{{ lookup('file', item) }}"  
#  with_fileglob:
#     - /cloud/ansible/pubkey/RKey/id_rsa.pub
#     - /cloud/ansible/pubkey/RKey/id_rsa

#- name: copy RKey to /root/.ssh/
#  copy:
#      src: /cloud/ansible/pubkey/RKey/
#      dest: /root/.ssh

#- name: Set up authorized keys for the ubuntu user
#  authorized_key: 
#       user: ops         
#       state: present
#       key: "{{ lookup('file', item) }}"
#  with_fileglob:
#     - /cloud/ansible/pubkey/Opskey/id_rsa.pub
#     - /cloud/ansible/pubkey/Opskey/id_rsa

- name: copy Opskey to /home/ops/.ssh/
  copy:
      src: /cloud/ansible/pubkey/Opskey/
      dest: /home/ops/.ssh
      remote_src: true
  become: true

- name: copy Rkey to /root/.ssh/
  copy:
      src: /cloud/ansible/pubkey/Opskey/
      dest: /root/.ssh
      remote_src: true
  become: true  

- name: Generate /etc/hosts file
  template:
    src=hosts.j2
    dest=/etc/hosts

- name: Create a /home/ops/cloud directory if it does not exist
  ansible.builtin.file:
    path: /home/ops/cloud
    state: directory
    mode: 1755

- name: copy multipass to /home/ops/cloud
  copy:
      src: /cloud/multipass/
      dest: /home/ops/cloud
      mode: 0755
      remote_src: true
  become: true 

- name: Execute cloud
ansible.builtin.shell: chmod +x /home/ops/cloud/*

- name: install packages
  apt:
      state: present
      name:
       - python3
       - pip
       - htop
       - nano
       - snapd
                 
