---

#- name: Update Upgrade
#  dnf:
#    name: "*"
#    state: latest

- name: Install sudo
  dnf:
     name: sudo
     state: present

- name: Allow 'sudo' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL:ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'


- name: Add sudoers users to sudo  group
  user:
    name="{{ item }}"
    groups=wheel
    append=yes
    state=present
    createhome=yes
  with_items:
        - ops
#        - nibiru
#        - ubuntu


- name: Set up authorized keys for the ops user
  authorized_key: 
       user: ops
       state: present
       key: "{{ lookup('file', item) }}"  
  with_fileglob:
     - /home/ops/.ssh/source.pub

#- name: Set up authorized keys for the nibiru user
#  authorized_key: 
#       user: nibiru         
#       state: present
#       key: "{{ lookup('file', item) }}"
#  with_fileglob:
#     - ~/ansible/pubkey/*

#- name: Set up authorized keys for the ubuntu user
#  authorized_key: 
#       user: ops         
#       state: present
#       key: "{{ lookup('file', item) }}"
#  with_fileglob:
#     - ~/ansible/pubkey/*


- name: Generate /etc/hosts file
  template:
    src=hosts.j2
    dest=/etc/hosts

    
