---
- name: Clone a ansible script github repository
  git:
    repo: https://github.com/Nieuwhof/ansible.git
    dest: ~/
    clone: yes
    update: yes

- name: Clone a multipass scripts github repository
  git:
    repo: https://github.com/Nieuwhof/multipass.git
    dest: ~/
    clone: yes
    update: yes

- name: Update Upgrade
  apt:
    name: "*"
    state: latest

- name: Set a hostname
  ansible.builtin.hostname:
    name: wallace

- name: Install sudo
  apt:
     name: sudo
     state: present

- name: Allow 'sudo' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL:ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'


- name: Add sudoers users to sudo group
  user:
    name="{{ item }}"
    groups=sudo
    append=yes
    state=present
    createhome=yes
  with_items:
        - ops

- name: Set up authorized keys for the root user
  authorized_key: 
       user: root
       state: present
       key: "{{ lookup('file', item) }}"  
  with_fileglob:
     - ~/ansible/pubkey/RKey/*

- name: Set up authorized keys for the ubuntu user
  authorized_key: 
       user: ops         
       state: present
       key: "{{ lookup('file', item) }}"
  with_fileglob:
     - ~/ansible/pubkey/Opskey/*

- name: Generate /etc/hosts file
  template:
    src=hosts.j2
    dest=/etc/hosts

- name: install packages
  apt:
      state: present
      name:
       - python3
       - pip
       - htop
       - nano
       - multipass                  
